CREATE TABLE IF NOT EXISTS public.user_permission 
(
  	id_user bigint NULL NULL,
  	id_permission bigint NOT NULL,
  	CONSTRAINT PK_USER_PERMISSION PRIMARY KEY (ID_USER, ID_PERMISSION),
	CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
	CONSTRAINT FK_PERMISSION FOREIGN KEY (ID_PERMISSION) REFERENCES PERMISSION (ID)
);