CREATE TABLE IF NOT EXISTS public.users_roles
(
  	id_user bigint NULL NULL,
  	id_role bigint NOT NULL,
  	CONSTRAINT PK_USER_ROLE PRIMARY KEY (ID_USER, ID_ROLE),
	CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USERS (ID),
	CONSTRAINT FK_ROLE FOREIGN KEY (ID_ROLE) REFERENCES ROLE (ID)
);